[package]
name = "nas-backup-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
walkdir = "2.5"
zip = "3.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3", "const_xxh3"] }

[[bin]]
name = "nas-backup-utils"
path = "main.rs"
